import { Hotspot } from '@/types/hotspot';

// Data Titik Panas Karhutla Indonesia (Format Standar NASA FIRMS VIIRS & MODIS)
// Data titik panas mencakup wilayah rawan karhutla: Riau, Sumsel, Jambi, Kalbar, Kalteng, Kalsel, Kaltim, Papua, Aceh

export const INDONESIA_HOTSPOTS: Hotspot[] = [
  // --- RIAU (Gambut Rawan Tinggi) ---
  {
    id: "IDN-FIRMS-001",
    latitude: 0.2312,
    longitude: 101.9845,
    brightness: 367.4,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "06:14",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 298.2,
    frp: 148.5,
    daynight: "D",
    province: "Riau",
    regency: "Pelalawan",
    district: "Teluk Meranti",
    land_type: "Lahan Gambut Dalam (>3m)",
    vegetation: "Semak Belukar & Hutan Sekunder",
    threat_level: "EXTREME"
  },
  {
    id: "IDN-FIRMS-002",
    latitude: 0.2450,
    longitude: 102.0120,
    brightness: 358.1,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "06:14",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 296.5,
    frp: 92.4,
    daynight: "D",
    province: "Riau",
    regency: "Pelalawan",
    district: "Teluk Meranti",
    land_type: "Lahan Gambut Sedang (1-2m)",
    vegetation: "Perkebunan & Semak",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-003",
    latitude: 1.4821,
    longitude: 101.9934,
    brightness: 372.0,
    scan: 0.41,
    track: 0.37,
    acq_date: "2026-10-09",
    acq_time: "18:22",
    satellite: "VIIRS Suomi-NPP",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 301.8,
    frp: 185.0,
    daynight: "N",
    province: "Riau",
    regency: "Bengkalis",
    district: "Rupat",
    land_type: "Kubah Gambut Pesisir",
    vegetation: "Hutan Rawa Gambut",
    threat_level: "EXTREME"
  },
  {
    id: "IDN-FIRMS-004",
    latitude: 1.5102,
    longitude: 102.0450,
    brightness: 344.2,
    scan: 0.41,
    track: 0.37,
    acq_date: "2026-10-09",
    acq_time: "18:22",
    satellite: "VIIRS Suomi-NPP",
    confidence: "nominal",
    version: "2.0NRT",
    bright_t31: 293.4,
    frp: 45.2,
    daynight: "N",
    province: "Riau",
    regency: "Bengkalis",
    district: "Rupat Utara",
    land_type: "Lahan Gambut Dangkal",
    vegetation: "Lahan Terbuka",
    threat_level: "MODERATE"
  },
  {
    id: "IDN-FIRMS-005",
    latitude: 1.6830,
    longitude: 101.4420,
    brightness: 361.7,
    scan: 1.0,
    track: 1.0,
    acq_date: "2026-10-09",
    acq_time: "03:45",
    satellite: "MODIS Terra",
    confidence: "88%",
    version: "6.1NRT",
    bright_t31: 299.1,
    frp: 110.3,
    daynight: "D",
    province: "Riau",
    regency: "Dumai",
    district: "Medang Kampai",
    land_type: "Lahan Gambut",
    vegetation: "Perkebunan Sawit & Semak",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-006",
    latitude: 0.8214,
    longitude: 101.8901,
    brightness: 339.8,
    scan: 0.39,
    track: 0.36,
    acq_date: "2026-10-08",
    acq_time: "06:30",
    satellite: "VIIRS NOAA-20",
    confidence: "nominal",
    version: "2.0NRT",
    bright_t31: 291.0,
    frp: 38.6,
    daynight: "D",
    province: "Riau",
    regency: "Siak",
    district: "Sungai Apit",
    land_type: "Lahan Gambut",
    vegetation: "Semak Belukar",
    threat_level: "MODERATE"
  },
  {
    id: "IDN-FIRMS-007",
    latitude: 2.1154,
    longitude: 100.5632,
    brightness: 355.6,
    scan: 0.40,
    track: 0.37,
    acq_date: "2026-10-09",
    acq_time: "18:22",
    satellite: "VIIRS Suomi-NPP",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 295.2,
    frp: 78.4,
    daynight: "N",
    province: "Riau",
    regency: "Rokan Hilir",
    district: "Tanah Putih",
    land_type: "Tanah Mineral & Gambut",
    vegetation: "Semak Belukar",
    threat_level: "HIGH"
  },

  // --- SUMATERA SELATAN (OKI, Banyuasin, Musi Banyuasin) ---
  {
    id: "IDN-FIRMS-010",
    latitude: -3.3421,
    longitude: 105.1245,
    brightness: 375.2,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "06:10",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 302.1,
    frp: 210.4,
    daynight: "D",
    province: "Sumatera Selatan",
    regency: "Ogan Komering Ilir",
    district: "Cengal",
    land_type: "Kubah Gambut Sangat Dalam (>4m)",
    vegetation: "Hutan Rawa Gambut Terdegradasi",
    threat_level: "EXTREME"
  },
  {
    id: "IDN-FIRMS-011",
    latitude: -3.3780,
    longitude: 105.1680,
    brightness: 369.8,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "06:10",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 299.7,
    frp: 164.2,
    daynight: "D",
    province: "Sumatera Selatan",
    regency: "Ogan Komering Ilir",
    district: "Cengal",
    land_type: "Lahan Gambut Dalam",
    vegetation: "Pakis & Purun",
    threat_level: "EXTREME"
  },
  {
    id: "IDN-FIRMS-012",
    latitude: -3.1205,
    longitude: 104.9812,
    brightness: 348.5,
    scan: 1.0,
    track: 1.0,
    acq_date: "2026-10-09",
    acq_time: "03:40",
    satellite: "MODIS Aqua",
    confidence: "79%",
    version: "6.1NRT",
    bright_t31: 294.0,
    frp: 62.1,
    daynight: "D",
    province: "Sumatera Selatan",
    regency: "Ogan Komering Ilir",
    district: "Pampangan",
    land_type: "Lebak Gambut",
    vegetation: "Lahan Pertanian & Belukar",
    threat_level: "MODERATE"
  },
  {
    id: "IDN-FIRMS-013",
    latitude: -2.4501,
    longitude: 104.4210,
    brightness: 356.9,
    scan: 0.39,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "18:18",
    satellite: "VIIRS Suomi-NPP",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 297.3,
    frp: 88.5,
    daynight: "N",
    province: "Sumatera Selatan",
    regency: "Banyuasin",
    district: "Muara Telang",
    land_type: "Lahan Gambut Pesisir",
    vegetation: "Semak Belukar",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-014",
    latitude: -2.7812,
    longitude: 103.8920,
    brightness: 342.3,
    scan: 0.40,
    track: 0.37,
    acq_date: "2026-10-08",
    acq_time: "06:25",
    satellite: "VIIRS NOAA-20",
    confidence: "nominal",
    version: "2.0NRT",
    bright_t31: 292.5,
    frp: 41.7,
    daynight: "D",
    province: "Sumatera Selatan",
    regency: "Musi Banyuasin",
    district: "Bayung Lencir",
    land_type: "Kawasan Konservasi & Gambut",
    vegetation: "Hutan Sekunder",
    threat_level: "MODERATE"
  },

  // --- JAMBI (Muaro Jambi & Tanjabtim) ---
  {
    id: "IDN-FIRMS-020",
    latitude: -1.4520,
    longitude: 103.8840,
    brightness: 366.1,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "06:12",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 299.8,
    frp: 135.8,
    daynight: "D",
    province: "Jambi",
    regency: "Muaro Jambi",
    district: "Kumpeh Ulu",
    land_type: "Kawasan Lindung Gambut",
    vegetation: "Hutan Rawa Terbakar",
    threat_level: "EXTREME"
  },
  {
    id: "IDN-FIRMS-021",
    latitude: -1.2140,
    longitude: 104.1120,
    brightness: 352.4,
    scan: 0.39,
    track: 0.37,
    acq_date: "2026-10-09",
    acq_time: "18:20",
    satellite: "VIIRS Suomi-NPP",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 296.0,
    frp: 74.3,
    daynight: "N",
    province: "Jambi",
    regency: "Tanjung Jabung Timur",
    district: "Dendang",
    land_type: "Lahan Gambut",
    vegetation: "Perkebunan & Semak",
    threat_level: "HIGH"
  },

  // --- KALIMANTAN BARAT (Ketapang, Kubu Raya, Sambas) ---
  {
    id: "IDN-FIRMS-030",
    latitude: -1.7820,
    longitude: 110.1240,
    brightness: 382.4,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "05:48",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 304.5,
    frp: 265.8,
    daynight: "D",
    province: "Kalimantan Barat",
    regency: "Ketapang",
    district: "Kendawangan",
    land_type: "Kubah Gambut Pesisir",
    vegetation: "Semak Belukar Gambut",
    threat_level: "EXTREME"
  },
  {
    id: "IDN-FIRMS-031",
    latitude: -1.7240,
    longitude: 110.0890,
    brightness: 371.1,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "05:48",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 301.2,
    frp: 172.0,
    daynight: "D",
    province: "Kalimantan Barat",
    regency: "Ketapang",
    district: "Kendawangan",
    land_type: "Lahan Gambut Dalam (>3m)",
    vegetation: "Hutan Rawa",
    threat_level: "EXTREME"
  },
  {
    id: "IDN-FIRMS-032",
    latitude: -1.5420,
    longitude: 109.9820,
    brightness: 350.6,
    scan: 1.0,
    track: 1.0,
    acq_date: "2026-10-09",
    acq_time: "04:10",
    satellite: "MODIS Terra",
    confidence: "82%",
    version: "6.1NRT",
    bright_t31: 295.4,
    frp: 85.0,
    daynight: "D",
    province: "Kalimantan Barat",
    regency: "Ketapang",
    district: "Matan Hilir Selatan",
    land_type: "Lahan Gambut",
    vegetation: "Semak Belukar",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-033",
    latitude: -0.1240,
    longitude: 109.4520,
    brightness: 349.2,
    scan: 0.39,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "17:55",
    satellite: "VIIRS Suomi-NPP",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 296.8,
    frp: 68.4,
    daynight: "N",
    province: "Kalimantan Barat",
    regency: "Kubu Raya",
    district: "Rasau Jaya",
    land_type: "Lahan Gambut",
    vegetation: "Pertanian & Semak Belukar",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-034",
    latitude: 1.3420,
    longitude: 109.2810,
    brightness: 338.5,
    scan: 0.40,
    track: 0.37,
    acq_date: "2026-10-08",
    acq_time: "06:05",
    satellite: "VIIRS NOAA-20",
    confidence: "nominal",
    version: "2.0NRT",
    bright_t31: 291.2,
    frp: 32.1,
    daynight: "D",
    province: "Kalimantan Barat",
    regency: "Sambas",
    district: "Paloh",
    land_type: "Tanah Pasir & Alang-alang",
    vegetation: "Semak Pantai",
    threat_level: "MODERATE"
  },

  // --- KALIMANTAN TENGAH (Pulang Pisau, Palangka Raya, Kotim, Katingan) ---
  {
    id: "IDN-FIRMS-040",
    latitude: -2.8520,
    longitude: 114.1280,
    brightness: 388.9,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "05:46",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 308.2,
    frp: 310.2,
    daynight: "D",
    province: "Kalimantan Tengah",
    regency: "Pulang Pisau",
    district: "Sebangau Kuala",
    land_type: "Taman Nasional Sebangau / Kubah Gambut",
    vegetation: "Hutan Rawa Gambut Dalam",
    threat_level: "EXTREME"
  },
  {
    id: "IDN-FIRMS-041",
    latitude: -2.7910,
    longitude: 114.1850,
    brightness: 374.3,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "05:46",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 303.4,
    frp: 198.6,
    daynight: "D",
    province: "Kalimantan Tengah",
    regency: "Pulang Pisau",
    district: "Kahayan Kuala",
    land_type: "Eks PLG (Proyek Lahan Gambut)",
    vegetation: "Kanal Kering & Pakis Gambut",
    threat_level: "EXTREME"
  },
  {
    id: "IDN-FIRMS-042",
    latitude: -2.2150,
    longitude: 113.8820,
    brightness: 358.4,
    scan: 0.39,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "17:52",
    satellite: "VIIRS Suomi-NPP",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 298.0,
    frp: 95.7,
    daynight: "N",
    province: "Kalimantan Tengah",
    regency: "Kota Palangka Raya",
    district: "Jekan Raya",
    land_type: "Lahan Gambut Pinggir Kota",
    vegetation: "Semak Belukar Kering",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-043",
    latitude: -2.5420,
    longitude: 112.9810,
    brightness: 351.2,
    scan: 1.0,
    track: 1.0,
    acq_date: "2026-10-09",
    acq_time: "04:15",
    satellite: "MODIS Terra",
    confidence: "80%",
    version: "6.1NRT",
    bright_t31: 295.2,
    frp: 72.8,
    daynight: "D",
    province: "Kalimantan Tengah",
    regency: "Kotawaringin Timur",
    district: "Mentawa Baru Ketapang",
    land_type: "Lahan Gambut Dangkal",
    vegetation: "Perkebunan & Belukar",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-044",
    latitude: -2.1890,
    longitude: 113.4120,
    brightness: 341.0,
    scan: 0.40,
    track: 0.37,
    acq_date: "2026-10-08",
    acq_time: "05:50",
    satellite: "VIIRS NOAA-20",
    confidence: "nominal",
    version: "2.0NRT",
    bright_t31: 292.0,
    frp: 39.4,
    daynight: "D",
    province: "Kalimantan Tengah",
    regency: "Katingan",
    district: "Katingan Hilir",
    land_type: "Lahan Gambut",
    vegetation: "Hutan Rawa Terdegradasi",
    threat_level: "MODERATE"
  },

  // --- KALIMANTAN SELATAN (Banjar & Barito Kuala) ---
  {
    id: "IDN-FIRMS-050",
    latitude: -3.4520,
    longitude: 114.7820,
    brightness: 362.5,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "05:45",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 299.1,
    frp: 118.4,
    daynight: "D",
    province: "Kalimantan Selatan",
    regency: "Banjar",
    district: "Gambut",
    land_type: "Lahan Gambut Pertanian",
    vegetation: "Jerami & Semak Belukar",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-051",
    latitude: -3.4750,
    longitude: 114.7210,
    brightness: 355.0,
    scan: 0.39,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "17:50",
    satellite: "VIIRS Suomi-NPP",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 297.0,
    frp: 86.2,
    daynight: "N",
    province: "Kalimantan Selatan",
    regency: "Kota Banjarbaru",
    district: "Landasan Ulin (Dekat Bandara)",
    land_type: "Gambut Rawan Asap Penerbangan",
    vegetation: "Purun & Semak",
    threat_level: "HIGH"
  },

  // --- KALIMANTAN TIMUR (Kutai Kartanegara & Berau) ---
  {
    id: "IDN-FIRMS-060",
    latitude: -0.4120,
    longitude: 117.1120,
    brightness: 345.8,
    scan: 0.39,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "05:42",
    satellite: "VIIRS NOAA-20",
    confidence: "nominal",
    version: "2.0NRT",
    bright_t31: 294.6,
    frp: 54.0,
    daynight: "D",
    province: "Kalimantan Timur",
    regency: "Kutai Kartanegara",
    district: "Muara Kaman",
    land_type: "Danau Rawa Gambut",
    vegetation: "Semak Belukar",
    threat_level: "MODERATE"
  },
  {
    id: "IDN-FIRMS-061",
    latitude: 2.1240,
    longitude: 117.4520,
    brightness: 338.2,
    scan: 1.0,
    track: 1.0,
    acq_date: "2026-10-08",
    acq_time: "03:55",
    satellite: "MODIS Terra",
    confidence: "74%",
    version: "6.1NRT",
    bright_t31: 291.5,
    frp: 35.8,
    daynight: "D",
    province: "Kalimantan Timur",
    regency: "Berau",
    district: "Segah",
    land_type: "Hutan Tanaman Industri",
    vegetation: "Lahan Terbuka",
    threat_level: "MODERATE"
  },

  // --- PAPUA & PAPUA SELATAN (Merauke & Mappi) ---
  {
    id: "IDN-FIRMS-070",
    latitude: -7.9820,
    longitude: 139.8540,
    brightness: 378.6,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "04:55",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 305.1,
    frp: 240.5,
    daynight: "D",
    province: "Papua Selatan",
    regency: "Merauke",
    district: "Kurik",
    land_type: "Savana & Rawa Gambut Musiman",
    vegetation: "Padang Rumput Ilalang Kering",
    threat_level: "EXTREME"
  },
  {
    id: "IDN-FIRMS-071",
    latitude: -8.1120,
    longitude: 140.1250,
    brightness: 364.2,
    scan: 0.38,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "04:55",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 300.4,
    frp: 145.2,
    daynight: "D",
    province: "Papua Selatan",
    regency: "Merauke",
    district: "Animha",
    land_type: "Savana & Hutan Terbuka",
    vegetation: "Rumput Liar Savana",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-072",
    latitude: -6.8520,
    longitude: 139.4210,
    brightness: 342.9,
    scan: 1.0,
    track: 1.0,
    acq_date: "2026-10-09",
    acq_time: "02:40",
    satellite: "MODIS Aqua",
    confidence: "81%",
    version: "6.1NRT",
    bright_t31: 293.8,
    frp: 61.3,
    daynight: "D",
    province: "Papua Selatan",
    regency: "Mappi",
    district: "Obaa",
    land_type: "Rawa Pedalaman",
    vegetation: "Belukar Rawa",
    threat_level: "MODERATE"
  },

  // --- ACEH & SUMATERA UTARA ---
  {
    id: "IDN-FIRMS-080",
    latitude: 4.1250,
    longitude: 96.1820,
    brightness: 354.2,
    scan: 0.39,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "06:18",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 297.4,
    frp: 81.6,
    daynight: "D",
    province: "Aceh",
    regency: "Aceh Barat",
    district: "Johan Pahlawan",
    land_type: "Rawa Gambut Pesisir",
    vegetation: "Semak Belukar",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-081",
    latitude: 3.8920,
    longitude: 96.3410,
    brightness: 341.5,
    scan: 0.40,
    track: 0.37,
    acq_date: "2026-10-08",
    acq_time: "18:25",
    satellite: "VIIRS Suomi-NPP",
    confidence: "nominal",
    version: "2.0NRT",
    bright_t31: 292.0,
    frp: 40.2,
    daynight: "N",
    province: "Aceh",
    regency: "Nagan Raya",
    district: "Darul Makmur",
    land_type: "Lahan Gambut Rawa Tripa",
    vegetation: "Kawasan Rawa Konservasi",
    threat_level: "MODERATE"
  },

  // --- SULAWESI & JAWA/NUSA TENGGARA (Savana & Gunung) ---
  {
    id: "IDN-FIRMS-090",
    latitude: -7.9420,
    longitude: 112.9520,
    brightness: 348.1,
    scan: 1.0,
    track: 1.0,
    acq_date: "2026-10-09",
    acq_time: "03:35",
    satellite: "MODIS Terra",
    confidence: "78%",
    version: "6.1NRT",
    bright_t31: 294.0,
    frp: 58.4,
    daynight: "D",
    province: "Jawa Timur",
    regency: "Probolinggo",
    district: "Sukapura (Bromo - Tengger)",
    land_type: "Lereng Pegunungan & Savana Bromo",
    vegetation: "Padang Rumput & Cemara Gunung",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-091",
    latitude: -8.5420,
    longitude: 120.4520,
    brightness: 351.0,
    scan: 0.39,
    track: 0.36,
    acq_date: "2026-10-09",
    acq_time: "05:15",
    satellite: "VIIRS NOAA-20",
    confidence: "high",
    version: "2.0NRT",
    bright_t31: 297.8,
    frp: 72.3,
    daynight: "D",
    province: "Nusa Tenggara Timur",
    regency: "Manggarai Timur",
    district: "Borong",
    land_type: "Padang Savana Kering",
    vegetation: "Rumput Kering & Semak Berduri",
    threat_level: "HIGH"
  },
  {
    id: "IDN-FIRMS-092",
    latitude: -1.2410,
    longitude: 120.1250,
    brightness: 335.7,
    scan: 0.40,
    track: 0.37,
    acq_date: "2026-10-08",
    acq_time: "05:30",
    satellite: "VIIRS NOAA-20",
    confidence: "low",
    version: "2.0NRT",
    bright_t31: 290.4,
    frp: 26.5,
    daynight: "D",
    province: "Sulawesi Tengah",
    regency: "Sigi",
    district: "Dolo Selatan",
    land_type: "Perbukitan & Hutan Terbuka",
    vegetation: "Belukar & Pertanian Kering",
    threat_level: "LOW"
  }
];
